### ISSUE TITLE
city/state route breaks when session cookie is removed

### ISSUE THREAD

**Issue by M0nica** [M0nica/flask_weather#54]
If I go to https://clima-weather.herokuapp.com/

it redirects to https://clima-weather.herokuapp.com/weather/New%20York/New%20York
(https://clima-weather.herokuapp.com/weather/{city}/{state})

if I delete my session cookie this url returns a 500 error:
https://clima-weather.herokuapp.com/weather/New%20York/New%20York
(https://clima-weather.herokuapp.com/weather/{city}/{state})

Steps to reproduce:
- go to the app
- delete session cookie 
- refresh page (and 500 error appears)

Desired functionality:

Allow users to navigate to city/state route regardless of their ip address/location

**Comment by M0nica** [comment]
@ming060 I think we should just honor the route and get the weather for that city/state if it’s valid. If it’s not a valid route then I think we should try to fetch city/state again but only if the weather for that route returns invalid data. Does that make sense?

**Comment by ming060** [comment]
@M0nica Yeap, that makes sense.

I think this issue (the 500 internal error) is due to the session does not contain the ip_info key.
So in the weather route, if the session does not contain the ip_info key.
I should run use the city/state info to get the weather data and return to the user.
Is that correct?
